### ISSUE TITLE
Upgrade dependencies

### ISSUE THREAD

**Issue by devinus** [jonathanKingston/broccoli-lint-eslint#8]
Using an up-to-date eslint will solve some of my problems.

**Comment by devinus** [comment]
I would do this myself, however I'm running into issues I can't solve since I'm not familiar with writing either eslint or broccoli plugins.

First of all, eslint no longer lints the project. I'm not sure if it ever did?

When I enable options that allow it to lint the project again, I run into this issue:

```
-> % npm test

> broccoli-lint-eslint@1.1.1 test /Users/devinus/Projects/broccoli-lint-eslint
> rm -rf build/ && npm run lint && broccoli build build > broccoli-build.out && node node_modules/mocha/bin/mocha build/test.js


> broccoli-lint-eslint@1.1.1 lint /Users/devinus/Projects/broccoli-lint-eslint
> eslint .

Error: Plugin subclasses must call the superclass constructor: Plugin.call(this, inputNodes)
    at EslintValidationFilter.Plugin.__broccoliGetInfo__ (/Users/devinus/Projects/broccoli-lint-eslint/node_modules/broccoli-plugin/index.js:55:43)
    at new ReadCompat (/Users/devinus/Projects/broccoli-lint-eslint/node_modules/broccoli-plugin/read_compat.js:15:33)
    at EslintValidationFilter.Plugin._initializeReadCompat (/Users/devinus/Projects/broccoli-lint-eslint/node_modules/broccoli-plugin/index.js:130:22)
    at EslintValidationFilter.Plugin.read (/Users/devinus/Projects/broccoli-lint-eslint/node_modules/broccoli-plugin/index.js:110:12)
    at /Users/devinus/Projects/broccoli-lint-eslint/node_modules/broccoli/lib/builder.js:106:23
    at lib$rsvp$$internal$$tryCatch (/Users/devinus/Projects/broccoli-lint-eslint/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/devinus/Projects/broccoli-lint-eslint/node_modules/rsvp/dist/rsvp.js:505:17)
    at /Users/devinus/Projects/broccoli-lint-eslint/node_modules/rsvp/dist/rsvp.js:1001:13
    at lib$rsvp$asap$$flush (/Users/devinus/Projects/broccoli-lint-eslint/node_modules/rsvp/dist/rsvp.js:1198:9)
    at doNTCallback0 (node.js:430:9)

Build failed
npm ERR! Test failed.  See above for more details.
```
